server:
  port: 8087
  servlet:
    context-path: /
  tomcat:
    max-threads: 200
    uri-encoding: UTF-8
    connection-timeout: 10000
spring:
  application:
    name: convert-demo
  aop:
    auto: true
logging:
  level:
    org.springframework.web: info
  config: classpath:logback/logback-spring.xml
save-dir:
  ppt-pdf-save-dir: D:\jmeterPPT\ppt-pdf
  word-pdf-save-dir: D:\jmeterPPT\word-pdf
  word-picture-save-dir: D:\jmeterPPT\word-picture
  pdf-picture-save-dir: D:\jmeterPPT\pdf-picture