server:
  port: 7077
  servlet:
    context-path: /
  tomcat:
    max-threads: 200
    uri-encoding: UTF-8
    connection-timeout: 10000
spring:
  application:
    name: convert-demo
  aop:
    auto: true
logging:
  level:
    org.springframework.web: info
  config: classpath:logback/logback-spring.xml
#转换之后保存的目录
save-dir:
  ppt-pdf-save-dir: /app/upload/office/ppt-pdf
  word-pdf-save-dir: /app/upload/office/word-pdf
  word-picture-save-dir: /app/upload/office/word-picture
  pdf-picture-save-dir: /app/upload/office/pdf-picture